version: '3.8'

services:
  # PostgreSQL for existing services and Zabbix
  postgres:
    image: postgres:15
    container_name: cultku_postgres
    environment:
      POSTGRES_DB: cultku
      POSTGRES_USER: cultku_user
      POSTGRES_PASSWORD: cultku_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cultku_user -d cultku"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cultku-network

  # NATS messaging
  nats:
    image: nats:2.10-alpine
    container_name: nats_server
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # HTTP monitoring
    command: [
      "-js",          # Enable JetStream
      "-sd", "/data",  # Storage directory
      "-m", "8222"     # Enable monitoring
    ]
    volumes:
      - nats_data:/data
    restart: unless-stopped
    networks:
      - cultku-network

  # Zabbix Database
  zabbix-postgres:
    image: postgres:15
    container_name: zabbix_postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data
    networks:
      - cultku-network

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix_server
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      ZBX_ENABLE_SNMP_TRAPS: "true"
    ports:
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix
      - ./monitoring/zabbix/templates:/usr/share/zabbix/templates
    depends_on:
      - zabbix-postgres
    networks:
      - cultku-network

  # Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix_web
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "America/New_York"
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
      - zabbix-postgres
    networks:
      - cultku-network

  # Zabbix Agent for monitoring services
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix_agent
    environment:
      ZBX_HOSTNAME: "NATS-Services-Host"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_ACTIVE_ALLOW: "true"
    volumes:
      - ./monitoring/zabbix/agent:/etc/zabbix/zabbix_agentd.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-server
    networks:
      - cultku-network
    privileged: true

  # Metrics exporter service
  metrics-exporter:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: metrics_exporter
    environment:
      - SERVICE_NAME=metrics_exporter
      - NATS_URL=nats://nats:4222
      - ZABBIX_SERVER=zabbix-server
    depends_on:
      - nats
      - zabbix-server
    restart: always
    volumes:
      - ./monitoring/metrics:/app/metrics
    networks:
      - cultku-network

  # Enhanced microservices with monitoring
  user_service:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: user_service
    environment:
      - SERVICE_NAME=user_service
      - NATS_URL=nats://nats:4222
      - ZABBIX_SERVER=zabbix-server
      - LOG_LEVEL=INFO
    depends_on:
      - nats
      - postgres
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - cultku-network

  notification_service:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: notification_service
    environment:
      - SERVICE_NAME=notification_service
      - NATS_URL=nats://nats:4222
      - ZABBIX_SERVER=zabbix-server
      - LOG_LEVEL=INFO
    depends_on:
      - nats
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - cultku-network

  analytics_service:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    container_name: analytics_service
    environment:
      - SERVICE_NAME=analytics_service
      - NATS_URL=nats://nats:4222
      - ZABBIX_SERVER=zabbix-server
      - LOG_LEVEL=INFO
    depends_on:
      - nats
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - cultku-network

volumes:
  postgres_data:
  nats_data:
  zabbix_postgres_data:
  zabbix_server_data:

networks:
  cultku-network:
    driver: bridge