"""Generated by cliffracer-generate-client. Do not edit.

service: shipments
version: 0.1.0
description: sha256:0209b3a088a979433f8b0cfb8098d28c1cbf81e49ed70347e4e0d1f63fb81122
namespace: retail
"""

import typing as _typing

from cliffracer.client import ServiceClient
from examples.virtual_services.shipments import Parcel, Receipt

SIGNATURES = {
    "ship": "sha256:1f74f5d647b25c25c84cd41ee7cef7f90391c993eeaa62d1a747916752050690",
}

_PARAM_TYPES: dict[str, dict[str, _typing.Any]] = {
    "ship": {
        "parcel": Parcel,
    },
}

_RETURN_TYPES: dict[str, _typing.Any] = {
    "ship": Receipt,
}

type _Return_ship = Receipt


class ShipmentsClient(ServiceClient):
    SERVICE = "shipments"
    NAMESPACE = "retail"
    VERSION = "0.1.0"
    DESCRIPTION_HASH = (
        "sha256:0209b3a088a979433f8b0cfb8098d28c1cbf81e49ed70347e4e0d1f63fb81122"
    )
    SIGNATURES = SIGNATURES

    async def ship(self, parcel: Parcel) -> Receipt:
        _result = await self._call(
            "ship",
            {
                "parcel": self._encode(parcel, _PARAM_TYPES["ship"]["parcel"]),
            },
            _RETURN_TYPES["ship"],
        )
        return _typing.cast(_Return_ship, _result)
