"""Generated by cliffracer-generate-client. Do not edit.

service: orders
version: 0.1.0
description: sha256:31dcb71d9e100038ab9c21759f4b7d40ee61ac2c5b5e31fa827266e9f978c24f
namespace: retail
"""

import typing as _typing

from cliffracer.client import ServiceClient

SIGNATURES = {
    "reserve": "sha256:c09fcab69b7c6179d2394436520f009edd33f7c2b0d0959de236ca6081593c56",
}

_PARAM_TYPES: dict[str, dict[str, _typing.Any]] = {
    "reserve": {
        "quantity": int,
    },
}

_RETURN_TYPES: dict[str, _typing.Any] = {
    "reserve": int,
}

type _Return_reserve = int


class OrdersClient(ServiceClient):
    SERVICE = "orders"
    NAMESPACE = "retail"
    VERSION = "0.1.0"
    DESCRIPTION_HASH = "sha256:31dcb71d9e100038ab9c21759f4b7d40ee61ac2c5b5e31fa827266e9f978c24f"
    SIGNATURES = SIGNATURES

    async def reserve(self, quantity: int) -> int:
        _result = await self._call(
            "reserve",
            {
                "quantity": self._encode(quantity, _PARAM_TYPES["reserve"]["quantity"]),
            },
            _RETURN_TYPES["reserve"],
        )
        return _typing.cast(_Return_reserve, _result)
