name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    
    services:
      nats:
        image: nats:2.10-alpine
        ports:
          - 4222:4222
        options: --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8222/healthz || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --extra dev
    
    - name: Lint with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    # Disabled: mypy has 332 errors, see TYPING_STATUS.md for roadmap
    # - name: Type check with mypy
    #   run: uv run mypy src/
    
    - name: Test with pytest (unit tests only)
      run: uv run pytest tests/unit/ -v --cov=src/cliffracer --cov-report=xml --tb=short
      env:
        NATS_SKIP_INTEGRATION: "true"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false